Repository CSW-Teams/MS3, pull requests merged in 2023-12, with the labels that each got.

#289 fix #261
  src/main/java/org/cswteams/ms3/control/scheduler/ControllerScheduler.java
Labels: Bug 🐞

#290 fix #287
  src/main/java/org/cswteams/ms3/entity/Desiderata.java
  src/main/java/org/cswteams/ms3/entity/Turno.java
  src/main/java/org/cswteams/ms3/entity/UserCategoryPolicy.java
  src/main/java/org/cswteams/ms3/entity/Utente.java
Labels: Bug 🐞

#308 fix #303
  pom.xml
  src/main/java/org/cswteams/ms3/entity/Turno.java
Labels: Task ✔️, Non Functional Requirement❕

#321 Implementazione dell'interfaccia di richiesta di ritiro dal turno
  frontend/src/components/common/CustomAppointmentComponents.js
  frontend/src/views/utente/ScheduleView.js
Labels: User Story 🗣️

#322 Issue #318: backend, + controller, + REST endpoint
  src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/ControllerRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/IControllerRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/control/utils/MappaRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/dao/RichiestaRimozioneDaTurnoDao.java
  src/main/java/org/cswteams/ms3/dto/RichiestaRimozioneDaTurnoDTO.java
  src/main/java/org/cswteams/ms3/entity/AssegnazioneTurno.java
  src/main/java/org/cswteams/ms3/entity/RichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/rest/RichiestaRimozioneDaTurnoRestEndpoint.java
Labels: User Story 🗣️

#324 Ref. #318 implementazione interfaccia
  frontend/src/API/RichiestaRimozioneDaTurnoAPI.js
  frontend/src/components/common/CustomAppointmentComponents.js
  frontend/src/views/utente/ScheduleView.js
Labels: User Story 🗣️

#330 Issue #318: backend, minor fixes and improvements
  src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/ControllerRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/IControllerRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/entity/RichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/rest/RichiestaRimozioneDaTurnoRestEndpoint.java
Labels: User Story 🗣️

#340 Issue #318 - backend, post-sprint 2
  src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/ControllerRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/IControllerRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/control/utils/MappaRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/dao/RichiestaRimozioneDaTurnoDao.java
  src/main/java/org/cswteams/ms3/dto/RichiestaRimozioneDaTurnoDTO.java
  src/main/java/org/cswteams/ms3/entity/RichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/rest/RichiestaRimozioneDaTurnoRestEndpoint.java
Labels: User Story 🗣️

#341 Issue #318: backend, functionality restore
  src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/ControllerRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/rest/RichiestaRimozioneDaTurnoRestEndpoint.java
Labels: User Story 🗣️

#342 Implementazione interfaccia di caricamento del file e di approvazione…
  frontend/src/API/RichiestaRimozioneDaTurnoAPI.js
  frontend/src/API/UploadFilesAPI.js
  frontend/src/components/common/BottomViewGestisciRitiro.js
  frontend/src/components/common/FilesUpload.js
  frontend/src/components/common/TabellaRichiesteRitiro.js
  frontend/src/routes.js
  frontend/src/views/utente/RichiesteRitiroView.js
  frontend/src/views/utente/ScheduleView.js
  frontend/src/views/utente/SingleScheduleView.js
  src/main/java/org/cswteams/ms3/control/utils/MappaRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/dto/RichiestaRimozioneDaTurnoDTO.java
Labels: User Story 🗣️

#343 Issue #318, backend, task B8
  src/main/java/org/cswteams/ms3/control/assegnazioneTurni/ControllerAssegnazioniTurni.java
  src/main/java/org/cswteams/ms3/control/assegnazioneTurni/IControllerAssegnazioneTurni.java
  src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/ControllerRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/IControllerRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/control/utils/MappaRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/dao/RichiestaRimozioneDaTurnoDao.java
  src/main/java/org/cswteams/ms3/dto/RichiestaRimozioneDaTurnoDTO.java
  src/main/java/org/cswteams/ms3/entity/AssegnazioneTurno.java
  src/main/java/org/cswteams/ms3/entity/RichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/rest/RichiestaRimozioneDaTurnoRestEndpoint.java
Labels: User Story 🗣️

#344 Issue #318 - modifiche a livello di interfaccia e bug fixing
  frontend/package.json
  frontend/src/API/RichiestaRimozioneDaTurnoAPI.js
  frontend/src/components/common/BottomViewGestisciRitiro.js
  frontend/src/components/common/CustomAppointmentComponents.js
  frontend/src/components/common/FilesUpload.js
  frontend/src/views/utente/RichiesteRitiroView.js
  frontend/src/views/utente/ScheduleView.js
  src/main/java/org/cswteams/ms3/control/assegnazioneTurni/ControllerAssegnazioniTurni.java
  src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/ControllerRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/IControllerRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/rest/RichiestaRimozioneDaTurnoRestEndpoint.java
Labels: User Story 🗣️

#346 Issue #318: backend, minor fixes
  src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/ControllerRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/control/utils/MappaRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/dto/RichiestaRimozioneDaTurnoDTO.java
  src/main/java/org/cswteams/ms3/rest/RichiestaRimozioneDaTurnoRestEndpoint.java
  src/main/resources/application.properties
Labels: User Story 🗣️

#347 Issue #318 - Completamento interfaccia di gestione dei ritiri
  frontend/src/API/RichiestaRimozioneDaTurnoAPI.js
  frontend/src/components/common/BottomViewGestisciRitiro.js
  frontend/src/components/common/TabellaRichiesteRitiro.js
  frontend/src/views/utente/RichiesteRitiroView.js
Labels: User Story 🗣️

#354 Issue 318 - merge
  frontend/package.json
  frontend/src/API/RichiestaRimozioneDaTurnoAPI.js
  frontend/src/API/UploadFilesAPI.js
  frontend/src/components/common/BottomViewGestisciRitiro.js
  frontend/src/components/common/CustomAppointmentComponents.js
  frontend/src/components/common/FilesUpload.js
  frontend/src/routes.js
  frontend/src/views/utente/GlobalScheduleView.js
  frontend/src/views/utente/RichiesteRitiroView.js
  frontend/src/views/utente/ScheduleView.js
  frontend/src/views/utente/SingleScheduleView.js
  src/main/java/org/cswteams/ms3/control/assegnazioneTurni/ControllerAssegnazioniTurni.java
  src/main/java/org/cswteams/ms3/control/assegnazioneTurni/IControllerAssegnazioneTurni.java
  src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/ControllerRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/IControllerRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/control/utils/MappaRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/dao/RichiestaRimozioneDaTurnoDao.java
  src/main/java/org/cswteams/ms3/dto/RichiestaRimozioneDaTurnoDTO.java
  src/main/java/org/cswteams/ms3/entity/AssegnazioneTurno.java
  src/main/java/org/cswteams/ms3/entity/RichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/rest/RichiestaRimozioneDaTurnoRestEndpoint.java
  src/main/resources/application.properties
Labels: User Story 🗣️

#361 Refactoring di RegistrazioneRestEndpoint e dto associati, ...
  frontend/src/views/utente/LoginView.js
  src/main/java/org/cswteams/ms3/control/login/ControllerLogin.java
  src/main/java/org/cswteams/ms3/control/login/IControllerLogin.java
  src/main/java/org/cswteams/ms3/control/passwordChange/IPasswordChange.java
  src/main/java/org/cswteams/ms3/control/passwordChange/PasswordChange.java
  src/main/java/org/cswteams/ms3/control/registrazione/ControllerRegistrazione.java
  src/main/java/org/cswteams/ms3/control/registrazione/IControllerRegistrazione.java
  src/main/java/org/cswteams/ms3/dao/UserDAO.java
  src/main/java/org/cswteams/ms3/dto/PasswordDTO.java
  src/main/java/org/cswteams/ms3/dto/RegistrazioneDTO.java
  src/main/java/org/cswteams/ms3/dto/changePassword/ChangePasswordDTO.java
  src/main/java/org/cswteams/ms3/dto/login/LoggedUserDTO.java
  src/main/java/org/cswteams/ms3/dto/login/LoginDTO.java
  src/main/java/org/cswteams/ms3/dto/registration/RegisteredUserDTO.java
  src/main/java/org/cswteams/ms3/dto/registration/RegistrationDTO.java
  src/main/java/org/cswteams/ms3/entity/Doctor.java
  src/main/java/org/cswteams/ms3/entity/User.java
  src/main/java/org/cswteams/ms3/exception/changePassword/WrongOldPasswordException.java
  src/main/java/org/cswteams/ms3/exception/login/InvalidRoleException.java
  src/main/java/org/cswteams/ms3/exception/registration/RegistrationException.java
  src/main/java/org/cswteams/ms3/rest/CambiaPasswordRestEndpoint.java
  src/main/java/org/cswteams/ms3/rest/LoginRestEndpoint.java
  src/main/java/org/cswteams/ms3/rest/RegistrazioneRestEndpoint.java
Labels: Non Functional Requirement❕

#363 Issue #246, RequestRemovalFromConcreteShift + GiustificazioneForzatura
  pom.xml
  src/main/java/org/cswteams/ms3/control/concreteShift/ConcreteShiftController.java
  src/main/java/org/cswteams/ms3/control/concreteShift/IConcreteShiftController.java
  src/main/java/org/cswteams/ms3/control/giustificaForzatura/ControllerGiustificaForzatura.java
  src/main/java/org/cswteams/ms3/control/giustificaForzatura/IControllerGiustificaForzatura.java
  src/main/java/org/cswteams/ms3/control/requestRemovalFromConcreteShift/IRequestRemovalFromConcreteShiftController.java
  src/main/java/org/cswteams/ms3/control/requestRemovalFromConcreteShift/RequestRemovalFromConcreteShiftController.java
  src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/ControllerRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/control/richiestaRimozioneDaTurno/IControllerRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/control/utils/MappaGiustificazioneForzaturaVincoli.java
  src/main/java/org/cswteams/ms3/control/utils/MappaRichiestaRimozioneDaTurno.java
  src/main/java/org/cswteams/ms3/dao/RequestRemovalFromConcreteShiftDAO.java
  src/main/java/org/cswteams/ms3/dto/RequestRemovalFromConcreteShiftDTO.java
  src/main/java/org/cswteams/ms3/entity/ConcreteShift.java
  src/main/java/org/cswteams/ms3/entity/DoctorAssignment.java
  src/main/java/org/cswteams/ms3/entity/RequestRemovalFromConcreteShift.java
  src/main/java/org/cswteams/ms3/rest/GiustificazioneForzaturaEndpoint.java
  src/main/java/org/cswteams/ms3/rest/RichiestaRimozioneDaTurnoRestEndpoint.java
Labels: Enabler 🔬
